using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using FluentAssertions;
using FluentMigrator;
using FluentMigrator.Runner;
using FluentMigrator.Runner.Initialization;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.DependencyInjection;
using Moq;
using Npgsql;
using NUnit.Framework;
using Newtonsoft.Json;
using Resgrid.Config;
using Resgrid.Model;
using Resgrid.Model.Inventories;
using Resgrid.Model.Repositories.Connection;
using Resgrid.Model.Repositories.Queries;
using Resgrid.Providers.Migrations.Migrations;
using Resgrid.Providers.MigrationsPg.Migrations;
using Resgrid.Repositories.DataRepository;
using Resgrid.Repositories.DataRepository.Configs;
using Resgrid.Repositories.DataRepository.Servers.SqlServer;
using Resgrid.Repositories.DataRepository.Transactions;

namespace Resgrid.Tests.Services
{
	[TestFixture(DatabaseTypes.SqlServer), TestFixture(DatabaseTypes.Postgres), NonParallelizable]
	public partial class InventoryDatabaseTests
	{
		private const string DatabasePrefix = "inventory_verification_";
		private const string MigrationRequest = "00000000-0000-0000-0000-000000000001";
		private readonly DatabaseTypes _type;
		private DatabaseTypes _previous;
		private string _master, _connection, _database;
		private bool _created, _configured;
		private ServiceProvider _runner;
		public InventoryDatabaseTests(DatabaseTypes type) { _type = type; }
		private string Q(string name) => _type == DatabaseTypes.Postgres ? name.ToLowerInvariant() : "[" + name + "]";
		private DbConnection Connect(string connection) => _type == DatabaseTypes.Postgres ? new NpgsqlConnection(connection) : new SqlConnection(connection);
		private SqlConfiguration Configuration() => _type == DatabaseTypes.Postgres ? new PostgreSqlConfiguration() : new SqlServerConfiguration();
		private IConnectionProvider Connections()
		{
			var provider = new Mock<IConnectionProvider>(); provider.Setup(p => p.Create()).Returns(() => Connect(_connection)); return provider.Object;
		}
		private InventoryStore Store(IUnitOfWork uow) => new(Connections(), Configuration(), uow, Mock.Of<IQueryFactory>());
		private static T NewRow<T>(int department = 77) where T : InventoryRow, new() => new()
		{ DepartmentId = department, CreatedBy = "inventory-test-author", CreatedOn = DateTime.UtcNow, ModifiedOn = DateTime.UtcNow, Content = "{}" };

		[OneTimeSetUp]
		public async Task CreateOnlyAnIsolatedInventoryDatabase()
		{
			var configured = Environment.GetEnvironmentVariable(_type == DatabaseTypes.Postgres ? "RESGRID_CHECKLIST_POSTGRES_TEST_CONNECTION" : "RESGRID_CHECKLIST_SQLSERVER_TEST_CONNECTION");
			if (string.IsNullOrWhiteSpace(configured)) Assert.Ignore("Set the checklist test connection for " + _type + " to enable disposable inventory database tests.");
			// A configured but inaccessible server is a failing fixture, never an environment skip.
			// Refuse application database names; the connection is used only to create a unique disposable database.
			if (_type == DatabaseTypes.Postgres)
			{
				var builder = new NpgsqlConnectionStringBuilder(configured);
				if (!string.IsNullOrEmpty(builder.Database) && builder.Database != "postgres" && builder.Database != "template1") throw new InvalidOperationException("Inventory tests require a PostgreSQL administrative database connection.");
				builder.Database = "postgres"; builder.IncludeErrorDetail = false; _master = builder.ConnectionString;
			}
			else
			{
				var builder = new SqlConnectionStringBuilder(configured);
				if (!string.IsNullOrEmpty(builder.InitialCatalog) && !string.Equals(builder.InitialCatalog, "master", StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException("Inventory tests require a SQL Server master connection.");
				builder.InitialCatalog = "master"; _master = builder.ConnectionString;
			}
			_previous = DataConfig.DatabaseType; _configured = true; DataConfig.DatabaseType = _type;
			_database = DatabasePrefix + Guid.NewGuid().ToString("N");
			await using (var master = Connect(_master)) { await master.ExecuteAsync("CREATE DATABASE " + _database); _created = true; }
			_connection = _type == DatabaseTypes.Postgres ? new NpgsqlConnectionStringBuilder(_master) { Database = _database }.ConnectionString
				: new SqlConnectionStringBuilder(_master) { InitialCatalog = _database }.ConnectionString;
			await using (var db = Connect(_connection))
			{
				var text = _type == DatabaseTypes.Postgres ? "varchar" : "nvarchar";
				var identity = _type == DatabaseTypes.Postgres ? "integer GENERATED BY DEFAULT AS IDENTITY" : "int IDENTITY(1,1)";
				var date = _type == DatabaseTypes.Postgres ? "timestamp" : "datetime2";
				var contactIdType = _type == DatabaseTypes.Postgres ? "citext" : "nvarchar(128)";
				if (_type == DatabaseTypes.Postgres)
				{
					await db.OpenAsync(); await db.ExecuteAsync("CREATE EXTENSION IF NOT EXISTS citext;");
					await ((NpgsqlConnection)db).ReloadTypesAsync();
				}
				await db.ExecuteAsync($@"CREATE TABLE {Q("Departments")} ({Q("DepartmentId")} int PRIMARY KEY);
INSERT INTO {Q("Departments")} VALUES(77),(88);
CREATE TABLE {Q("Contacts")} ({Q("ContactId")} {contactIdType} PRIMARY KEY, {Q("DepartmentId")} int NOT NULL);
CREATE TABLE {Q("DepartmentGroups")} ({Q("DepartmentGroupId")} int PRIMARY KEY, {Q("DepartmentId")} int NOT NULL);
INSERT INTO {Q("DepartmentGroups")} VALUES(123,77),(223,88);
CREATE TABLE {Q("Units")} ({Q("UnitId")} int PRIMARY KEY, {Q("DepartmentId")} int NOT NULL);
INSERT INTO {Q("Units")} VALUES(12,77),(13,77),(22,88);
CREATE TABLE {Q("AspNetUsers")} ({Q("Id")} {text}(128) PRIMARY KEY);
INSERT INTO {Q("AspNetUsers")} VALUES('inventory-test-author'),('inventory-test-other');
CREATE TABLE {Q("InventoryTypes")} ({Q("InventoryTypeId")} {identity} PRIMARY KEY, {Q("DepartmentId")} int NOT NULL, {Q("Type")} {text}(250) NOT NULL);
CREATE TABLE {Q("Inventories")} ({Q("InventoryId")} {identity} PRIMARY KEY, {Q("DepartmentId")} int NOT NULL, {Q("TypeId")} int NOT NULL, {Q("Amount")} decimal(24,6) NOT NULL);
CREATE TABLE {Q("RmsRecordLegalHolds")} ({Q("Id")} {text}(36) PRIMARY KEY, {Q("DepartmentId")} int NOT NULL, {Q("ReleasedOn")} {date} NULL);
CREATE TABLE {Q("WorkflowRuns")} ({Q("WorkflowRunId")} {text}(36) PRIMARY KEY, {Q("DepartmentId")} int NOT NULL, {Q("TriggerEventType")} int NOT NULL, {Q("InputPayload")} {text}(250));
CREATE TABLE {Q("WorkflowRunLogs")} ({Q("WorkflowRunLogId")} {text}(36) PRIMARY KEY, {Q("WorkflowRunId")} {text}(36) NOT NULL REFERENCES {Q("WorkflowRuns")}({Q("WorkflowRunId")}), {Q("RenderedOutput")} {text}(250));
CREATE TABLE {Q("DomainEventOutbox")} ({Q("Id")} {text}(36) PRIMARY KEY, {Q("DepartmentId")} int NOT NULL, {Q("ProducerSubsystem")} {text}(64) NOT NULL, {Q("Payload")} {text}(250));
CREATE TABLE {Q("AuditLogs")} ({Q("Id")} {text}(36) PRIMARY KEY, {Q("DepartmentId")} int NOT NULL, {Q("LogType")} int NOT NULL, {Q("Content")} {text}(250));");
			}
			var source = new Mock<IMigrationSource>(); source.Setup(s => s.GetMigrations()).Returns(new IMigration[]
			{
				_type == DatabaseTypes.Postgres ? new M0197_AddWorkOrdersPg() : new M0197_AddWorkOrders(),
                _type == DatabaseTypes.Postgres ? new M0198_AddInventoryModernizationPg() : new M0198_AddInventoryModernization(),
				_type == DatabaseTypes.Postgres ? new M0199_FenceLegacyInventoryWritesPg() : new M0199_FenceLegacyInventoryWrites(),
				_type == DatabaseTypes.Postgres ? new M0200_AddRecordInventoryUsagePg() : new M0200_AddRecordInventoryUsage(),
				_type == DatabaseTypes.Postgres ? new M0201_AddInventoryPurchasingPg() : new M0201_AddInventoryPurchasing(),
				_type == DatabaseTypes.Postgres ? new M0202_AddInventoryCountsAndAlertsPg() : new M0202_AddInventoryCountsAndAlerts(),
                _type == DatabaseTypes.Postgres ? new M0203_AddWorkOrderIntegrationsPg() : new M0203_AddWorkOrderIntegrations(),
                _type == DatabaseTypes.Postgres ? new M0204_AddWorkOrderRecurrencesPg() : new M0204_AddWorkOrderRecurrences(),
				_type == DatabaseTypes.Postgres ? new M0205_EnforceInventoryTenantHoldersPg() : new M0205_EnforceInventoryTenantHolders(),
                _type == DatabaseTypes.Postgres ? new M0206_AddWorkOrderReportingPg() : new M0206_AddWorkOrderReporting(),
                _type == DatabaseTypes.Postgres ? new M0207_AddWorkOrderOperationsPg() : new M0207_AddWorkOrderOperations()
			});
			_runner = new ServiceCollection().AddFluentMigratorCore().ConfigureRunner(r =>
			{
				if (_type == DatabaseTypes.Postgres) r.AddPostgres(); else r.AddSqlServer(); r.WithGlobalConnectionString(_connection);
			}).AddSingleton(source.Object).BuildServiceProvider();
			_runner.GetRequiredService<IMigrationRunner>().MigrateUp();
		}

		[SetUp]
		public async Task ClearOnlyThisFixturesInventoryRows()
		{
			await using var db = Connect(_connection);
			foreach (var table in new[] { "WorkflowRunLogs", "WorkflowRuns", "DomainEventOutbox", "AuditLogs", "RmsRecordLegalHolds" })
				await db.ExecuteAsync("DELETE FROM " + Q(table));
			await db.ExecuteAsync($"UPDATE {Q("InventoryCountItems")} SET {Q("TransactionId")}=NULL");
			foreach (var table in new[] { "InventoryAlertDeliveries", "InventoryAlerts", "RecordInventoryUsages", "InventoryTransferItems", "InventoryTransactions", "InventoryCountItems", "InventoryCounts", "InventoryPurchaseOrderItems", "InventoryPurchaseOrders", "InventoryVendors", "InventoryIssuances", "InventoryTransfers", "InventoryStocks", "InventoryKitItems" })
				await db.ExecuteAsync("DELETE FROM " + Q(table));
			await db.ExecuteAsync($"UPDATE {Q("InventoryAssets")} SET {Q("CurrentLocationId")}=NULL");
			foreach (var table in new[] { "InventoryLocations", "InventoryAssets", "InventoryLots", "InventoryItems", "InventoryCategories", "InventoryKits", "InventoryOperations", "Inventories", "InventoryTypes", "Contacts" })
				await db.ExecuteAsync("DELETE FROM " + Q(table));
		}

		[OneTimeTearDown]
		public async Task RemoveOnlyThisFixturesDatabase()
		{
			_runner?.Dispose(); if (_configured) DataConfig.DatabaseType = _previous;
			if (!_created) return;
			if (!_database.StartsWith(DatabasePrefix, StringComparison.Ordinal) || !Guid.TryParseExact(_database.Substring(DatabasePrefix.Length), "N", out _)) throw new InvalidOperationException("Unexpected inventory fixture database name.");
			if (_type == DatabaseTypes.Postgres) NpgsqlConnection.ClearAllPools(); else SqlConnection.ClearAllPools();
			await using var master = Connect(_master);
			await master.ExecuteAsync(_type == DatabaseTypes.Postgres ? "DROP DATABASE " + _database + " WITH (FORCE)"
				: "ALTER DATABASE " + _database + " SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE " + _database);
		}

		private async Task WriteAsync(Func<InventoryStore, Task> work, int department = 77)
		{
			using var uow = new UnitOfWork(Connections()); var store = Store(uow);
			await uow.CreateOrGetConnectionAsync(); await store.LockDepartmentAsync(department);
			try { await work(store); uow.CommitChanges(); } catch { uow.DiscardChanges(); throw; }
		}
		private async Task RejectAsync(Func<InventoryStore, Task> work)
		{
			using var uow = new UnitOfWork(Connections()); var store = Store(uow);
			await uow.CreateOrGetConnectionAsync(); await store.LockDepartmentAsync(77);
			try { await FluentActions.Awaiting(() => work(store)).Should().ThrowAsync<DbException>(); } finally { uow.DiscardChanges(); }
		}
		private async Task<(InventoryItem Item, InventoryLocation Location)> SeedAsync(int department = 77)
		{
			var item = NewRow<InventoryItem>(department); var location = NewRow<InventoryLocation>(department);
			await WriteAsync(async store => { await store.InsertAsync(item); await store.InsertAsync(location); }, department); return (item, location);
		}
		private async Task<string> InsertContactAsync(int department = 77, string contactId = null)
		{
			contactId ??= Guid.NewGuid().ToString("D");
			await using var db = Connect(_connection);
			await db.ExecuteAsync($"INSERT INTO {Q("Contacts")} ({Q("ContactId")},{Q("DepartmentId")}) VALUES(@contactId,@department)", new { contactId, department });
			return contactId;
		}
		private async Task<(InventoryVendor Vendor, InventoryPurchaseOrder Order, InventoryPurchaseOrderItem Line, InventoryItem Item, InventoryLocation Location)> SeedPurchasingAsync(int department = 77)
		{
			var seed = await SeedAsync(department);
			var vendor = NewRow<InventoryVendor>(department); vendor.ContactId = await InsertContactAsync(department);
			var order = NewRow<InventoryPurchaseOrder>(department); order.VendorId = vendor.Id; order.CurrencyCode = "USD";
			var line = PurchaseLine(order, seed.Item);
			await WriteAsync(async store => { await store.InsertAsync(vendor); await store.InsertAsync(order); await store.InsertAsync(line); }, department);
			return (vendor, order, line, seed.Item, seed.Location);
		}
		private static InventoryPurchaseOrderItem PurchaseLine(InventoryPurchaseOrder order, InventoryItem item, int lineNumber = 1)
		{
			var row = NewRow<InventoryPurchaseOrderItem>(order.DepartmentId); row.PurchaseOrderId = order.Id; row.ItemId = item.Id;
			row.LineNumber = lineNumber; row.QuantityOrdered = 3.123456m; return row;
		}
		private static InventoryTransaction Receipt(InventoryPurchaseOrder order, InventoryPurchaseOrderItem line, InventoryItem item, InventoryLocation location, decimal quantity = 0.123456m)
		{
			var row = Posting(item, null, location, quantity); row.ReferenceType = (int)InventoryReferenceType.PurchaseOrder;
			row.ReferenceId = order.Id; row.PurchaseOrderItemId = line.Id; return row;
		}
		private static InventoryTransaction Posting(InventoryItem item, InventoryLocation from, InventoryLocation to, decimal quantity, InventoryTransactionType type = InventoryTransactionType.Receive)
		{
			var row = NewRow<InventoryTransaction>(item.DepartmentId); row.ItemId = item.Id; row.FromLocationId = from?.Id; row.ToLocationId = to?.Id;
			row.Quantity = quantity; row.TransactionType = (int)type; row.OccurredOn = DateTime.UtcNow; return row;
		}
		private static RecordInventoryUsage Usage(InventoryTransaction transaction, string sourceId = null)
		{
			var row = NewRow<RecordInventoryUsage>(transaction.DepartmentId);
			row.SourceType = (int)InventoryUsageSourceType.RmsRecord; row.SourceId = sourceId ?? Guid.NewGuid().ToString("D");
			row.RecordKind = (int)RmsRecordKind.Operational; row.ItemId = transaction.ItemId; row.AssetId = transaction.AssetId; row.LotId = transaction.LotId;
			row.SourceLocationId = transaction.FromLocationId ?? transaction.ToLocationId; row.Quantity = transaction.Quantity;
			row.TransactionId = transaction.Id; return row;
		}
		private async Task MarkMigratedAsync(int department = 77)
		{
			var marker = NewRow<InventoryOperation>(department); marker.RequestId = MigrationRequest; marker.State = 2;
			await WriteAsync(store => store.InsertAsync(marker), department);
		}
		private async Task<int> InsertLegacyTypeAsync(DbConnection db, int department)
		{
			return await db.ExecuteScalarAsync<int>($"INSERT INTO {Q("InventoryTypes")} ({Q("DepartmentId")},{Q("Type")}) VALUES(@department,'synthetic legacy type') {(_type == DatabaseTypes.Postgres ? "RETURNING inventorytypeid" : "; SELECT CAST(SCOPE_IDENTITY() AS int);")}", new { department });
		}
		private Task<int> LegacyCountAsync(DbConnection db, string table, int department) => db.ExecuteScalarAsync<int>($"SELECT COUNT(*) FROM {Q(table)} WHERE {Q("DepartmentId")}=@department", new { department });

		private async Task SeedCleanupEvidenceAsync(int department = 77)
		{
			await using var db = Connect(_connection);
			var legacyType = await InsertLegacyTypeAsync(db, department);
			await db.ExecuteAsync($"INSERT INTO {Q("Inventories")} ({Q("DepartmentId")},{Q("TypeId")},{Q("Amount")}) VALUES(@department,@legacyType,1)", new { department, legacyType });
			T Protected<T>() where T : InventoryRow, new()
			{
				var row = NewRow<T>(department); row.IsProtected = true; row.Content = "SYNTHETIC-OPAQUE-PROTECTED-EVIDENCE"; return row;
			}
			var category = Protected<InventoryCategory>(); var subcategory = Protected<InventoryCategory>(); subcategory.ParentCategoryId = category.Id;
			var item = Protected<InventoryItem>(); item.CategoryId = subcategory.Id;
			var vendor = Protected<InventoryVendor>(); vendor.ContactId = await InsertContactAsync(department);
			var order = Protected<InventoryPurchaseOrder>(); order.VendorId = vendor.Id; order.CurrencyCode = "USD";
			order.Status = (int)InventoryPurchaseOrderStatus.PartiallyReceived; order.OrderedOn = DateTime.UtcNow;
			var orderLine = Protected<InventoryPurchaseOrderItem>(); orderLine.PurchaseOrderId = order.Id; orderLine.ItemId = item.Id;
			orderLine.LineNumber = 1; orderLine.QuantityOrdered = 3.123456m; orderLine.QuantityReceived = 0.123456m;
			var facility = Protected<InventoryLocation>(); var child = Protected<InventoryLocation>(); child.ParentLocationId = facility.Id;
			var receipt = Receipt(order, orderLine, item, child); receipt.IsProtected = true; receipt.Content = "SYNTHETIC-OPAQUE-RECEIPT-EVIDENCE";
			var lot = Protected<InventoryLot>(); lot.ItemId = item.Id; lot.ReceivedOn = DateTime.UtcNow;
			var containerAsset = Protected<InventoryAsset>(); containerAsset.ItemId = item.Id; containerAsset.LotId = lot.Id; containerAsset.CurrentLocationId = child.Id;
			var container = Protected<InventoryLocation>(); container.LocationType = (int)InventoryLocationType.Container; container.ContainerAssetId = containerAsset.Id;
			var asset = Protected<InventoryAsset>(); asset.ItemId = item.Id; asset.LotId = lot.Id; asset.CurrentLocationId = container.Id;
			var stock = Protected<InventoryStock>(); stock.ItemId = item.Id; stock.LocationId = container.Id; stock.LotId = lot.Id; stock.Quantity = 0.123456m;
			var operation = Protected<InventoryOperation>(); operation.RequestId = MigrationRequest; operation.State = 2;
			var issuance = Protected<InventoryIssuance>(); issuance.ItemId = item.Id; issuance.AssetId = asset.Id; issuance.LotId = lot.Id;
			issuance.LocationId = container.Id; issuance.IssuedToUserId = "inventory-test-author"; issuance.Quantity = 1; issuance.IssuedOn = DateTime.UtcNow;
			var transaction = Protected<InventoryTransaction>(); transaction.ItemId = item.Id; transaction.AssetId = asset.Id; transaction.LotId = lot.Id;
			transaction.OperationId = operation.Id; transaction.TransactionType = (int)InventoryTransactionType.Transfer; transaction.FromLocationId = child.Id;
			transaction.ToLocationId = container.Id; transaction.Quantity = 1; transaction.OccurredOn = DateTime.UtcNow; transaction.IssuanceId = issuance.Id;
			var reversal = Protected<InventoryTransaction>(); reversal.ItemId = item.Id; reversal.TransactionType = (int)InventoryTransactionType.Return;
			reversal.Quantity = 1; reversal.OccurredOn = DateTime.UtcNow; reversal.ReversesTransactionId = transaction.Id; reversal.FromLocationId = container.Id; reversal.ToLocationId = child.Id;
			var transfer = Protected<InventoryTransfer>(); transfer.OperationId = operation.Id; transfer.FromLocationId = child.Id; transfer.ToLocationId = container.Id;
			var transferItem = Protected<InventoryTransferItem>(); transferItem.TransferId = transfer.Id; transferItem.TransactionId = transaction.Id;
			transferItem.ItemId = item.Id; transferItem.AssetId = asset.Id; transferItem.LotId = lot.Id; transferItem.Quantity = 1;
			var kit = Protected<InventoryKit>(); var kitItem = Protected<InventoryKitItem>(); kitItem.KitId = kit.Id; kitItem.ItemId = item.Id; kitItem.Quantity = 1;
			var usage = Usage(transaction); usage.IsProtected = true; usage.Content = "SYNTHETIC-OPAQUE-USAGE-EVIDENCE";
			var correctedUsage = Usage(reversal, usage.SourceId); correctedUsage.ReversesUsageId = usage.Id;
			correctedUsage.IsProtected = true; correctedUsage.Content = "SYNTHETIC-OPAQUE-CORRECTION-EVIDENCE";
			var count = Protected<InventoryCount>(); count.LocationId = child.Id; count.Status = 2; count.SnapshotFingerprint = new string('A', 64); count.SnapshotOn = DateTime.UtcNow; count.CompletedOn = DateTime.UtcNow; count.OperationId = operation.Id;
			var countLine = Protected<InventoryCountItem>(); countLine.CountId = count.Id; countLine.ItemId = item.Id; countLine.LocationId = child.Id; countLine.ExpectedQuantity = 1; countLine.CountedQuantity = 2;
			var countMovement = Protected<InventoryTransaction>(); countMovement.ItemId = item.Id; countMovement.ToLocationId = child.Id; countMovement.Quantity = 1; countMovement.OccurredOn = DateTime.UtcNow;
			countMovement.OperationId = operation.Id; countMovement.LineNumber = 99; countMovement.CountItemId = countLine.Id; countMovement.TransactionType = 7; countMovement.ReferenceType = 7; countMovement.ReferenceId = count.Id;
			var alert = NewRow<InventoryAlert>(department); alert.ItemId = item.Id; alert.LocationId = child.Id; alert.DedupKey = new string('B', 64); alert.OpenedOn = DateTime.UtcNow;
			var delivery = NewRow<InventoryAlertDelivery>(department); delivery.AlertId = alert.Id; delivery.UserId = "inventory-test-author"; delivery.NextAttemptOn = DateTime.UtcNow;
			alert.Content = null; delivery.Content = null;
			await WriteAsync(async store =>
			{
				await store.InsertAsync(category); await store.InsertAsync(subcategory); await store.InsertAsync(item);
				await store.InsertAsync(vendor); await store.InsertAsync(order); await store.InsertAsync(orderLine);
				await store.InsertAsync(facility); await store.InsertAsync(child); await store.InsertAsync(lot); await store.InsertAsync(containerAsset);
				await store.InsertAsync(receipt);
				await store.InsertAsync(container); await store.InsertAsync(asset); await store.InsertAsync(stock); await store.InsertAsync(operation);
				await store.InsertAsync(issuance); await store.InsertAsync(transaction); await store.InsertAsync(reversal);
				await store.InsertAsync(usage); await store.InsertAsync(correctedUsage);
				await store.InsertAsync(transfer); await store.InsertAsync(transferItem); await store.InsertAsync(kit); await store.InsertAsync(kitItem);
				await store.InsertAsync(count); await store.InsertAsync(countLine); await store.InsertAsync(countMovement);
				countLine.TransactionId = countMovement.Id; countLine.Revision++; await store.UpdateAsync(countLine, countLine.Revision - 1);
				await store.InsertAsync(alert); await store.InsertAsync(delivery);
			}, department);
			foreach (var trigger in InventoryWorkflowPayload.Triggers.Concat(new[] { 0, 67, 70 }))
			{
				var run = Guid.NewGuid().ToString("D"); var log = Guid.NewGuid().ToString("D"); var outbox = Guid.NewGuid().ToString("D");
				var producer = trigger == 0 ? "Records" : trigger == 67 ? "Checklists" : trigger == 70 ? "WorkOrders" : "Inventory";
				await db.ExecuteAsync($@"INSERT INTO {Q("WorkflowRuns")} VALUES(@run,@department,@trigger,'SYNTHETIC-OPAQUE-WORKFLOW');
INSERT INTO {Q("WorkflowRunLogs")} VALUES(@log,@run,'SYNTHETIC-OPAQUE-LOG');
INSERT INTO {Q("DomainEventOutbox")} VALUES(@outbox,@department,@producer,'SYNTHETIC-OPAQUE-EVENT');", new { run, log, outbox, department, trigger, producer });
			}
			await db.ExecuteAsync($"INSERT INTO {Q("AuditLogs")} VALUES(@inventory,@department,@inventoryType,'SYNTHETIC-INVENTORY-AUDIT'),(@other,@department,0,'SYNTHETIC-OTHER-AUDIT')",
				new { inventory = Guid.NewGuid().ToString("D"), other = Guid.NewGuid().ToString("D"), department, inventoryType = (int)AuditLogTypes.InventoryChanged });
		}

		private async Task<Dictionary<string, string>> CleanupSnapshotAsync(DbConnection db, int? department = null)
		{
			var snapshot = new Dictionary<string, string>();
			foreach (var table in InventoryTables.All.Values.Concat(new[] { "WorkflowRuns", "WorkflowRunLogs", "DomainEventOutbox", "AuditLogs", "RmsRecordLegalHolds", "Inventories", "InventoryTypes", "Contacts" }))
			{
				var scope = !department.HasValue ? "" : table == "WorkflowRunLogs"
					? $" WHERE {Q("WorkflowRunId")} IN (SELECT {Q("WorkflowRunId")} FROM {Q("WorkflowRuns")} WHERE {Q("DepartmentId")}=@department)"
					: $" WHERE {Q("DepartmentId")}=@department";
				snapshot[table] = JsonConvert.SerializeObject(await db.QueryAsync($"SELECT * FROM {Q(table)}{scope} ORDER BY 1,2", new { department }));
			}
			return snapshot;
		}
	}
}
