namespace Resgrid.Model.Events
{
	public class UnitStatusEvent
	{
		public int DepartmentId { get; set; }
		public UnitState Status { get; set; }
		public UnitState PreviousStatus { get; set; }

		/// <summary>
		/// True when the status change was made by an automated process (i.e. call dispatch auto-status)
		/// and not directly by a user. Automated changes should not generate user notifications.
		/// </summary>
		public bool AutoGenerated { get; set; }
	}
}