namespace Resgrid.Model.Events
{
	public class UserStaffingEvent
	{
		public int DepartmentId { get; set; }
		public UserState Staffing { get; set; }
		public UserState PreviousStaffing { get; set; }

		/// <summary>
		/// True when the staffing change was made by an automated process (i.e. scheduled department reset)
		/// and not directly by a user. Automated changes should not generate user notifications.
		/// </summary>
		public bool AutoGenerated { get; set; }
	}
}