// <auto-generated />
namespace Resgrid.Repositories.DataRepository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedMaxLengthToUnitLogNarrative : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedMaxLengthToUnitLogNarrative));
        
        string IMigrationMetadata.Id
        {
            get { return "201304161529530_AddedMaxLengthToUnitLogNarrative"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
