<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Configurations>Debug;Release;Docker</Configurations>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="FluentAssertions" Version="8.2.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="NUnit" Version="4.3.2" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Core\Resgrid.Model\Resgrid.Model.csproj" />
		<ProjectReference Include="..\..\Providers\Resgrid.Providers.Tracking\Resgrid.Providers.Tracking.csproj" />
		<ProjectReference Include="..\..\Workers\Resgrid.TrackerGateway\Resgrid.TrackerGateway.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Data\Gt06\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Queclink\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Teltonika\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
