namespace Resgrid.Model
{
	public enum AuditLogTypes
	{
		DepartmentSettingsChanged,
		UserAdded,
		UserRemoved,
		GroupAdded,
		GroupRemoved,
		GroupChanged,
		UnitAdded,
		UnitRemoved,
		UnitChanged,
		ProfileUpdated,
		PermissionsChanged,
		SubscriptionUpdated,
		SubscriptionCreated,
		SubscriptionCancelled,
		SubscriptionBillingInfoUpdated,
		// New
		CallReactivated,
		UserAccountDeleted,
		AddonSubscriptionModified,
		DeleteDepartmentRequested,
		DeleteDepartmentRequestedCancelled,
		DeleteStaticShift,
		UpdateStaticShift,
		// New 7-13-2024
		CustomStatusAdded,
		CustomStatusRemoved,
		CustomStatusUpdated,
		CustomStatusDetailUpdated,
		CallTypeAdded,
		CallTypeEdited,
		CallTypeRemoved,
		CallPriorityAdded,
		CallPriorityEdited,
		CallPriorityRemoved,
		UnitTypeAdded,
		UnitTypeEdited,
		UnitTypeRemoved,
		CertificationTypeAdded,
		CertificationTypeEdited,
		CertificationTypeRemoved,
		DocumentCategoryAdded,
		DocumentCategoryEdited,
		DocumentCategoryRemoved,
		DocumentAdded,
		DocumentEdited,
		DocumentRemoved,
		NoteCategoryAdded,
		NoteCategoryEdited,
		NoteCategoryRemoved,
		NoteAdded,
		NoteEdited,
		NoteRemoved,
		ContactAdded,
		ContactEdited,
		ContactRemoved,
		ContactCategoryAdded,
		ContactCategoryEdited,
		ContactCategoryRemoved,
		ContactNoteTypeAdded,
		ContactNoteTypeEdited,
		ContactNoteTypeRemoved,
		// Workflow operations
		WorkflowAdded,
		WorkflowEdited,
		WorkflowDeleted,
		WorkflowStepAdded,
		WorkflowStepEdited,
		WorkflowStepDeleted,
		WorkflowCredentialAdded,
		WorkflowCredentialEdited,
		WorkflowCredentialDeleted,
		// Contact verification
		ContactVerificationCodeSent,
		ContactVerificationConfirmed,
		ContactVerificationFailed,
		// Two-factor authentication
		TwoFactorEnabled,
		TwoFactorDisabled,
		TwoFactorLoginVerified,
		TwoFactorRecoveryCodeUsed,
		TwoFactorStepUpVerified,
		// SSO / SAML / OIDC
		SsoConfigCreated,
		SsoConfigUpdated,
		SsoConfigDeleted,
		SsoLoginSucceeded,
		SsoLoginFailed,
		SsoUserProvisioned,
		// SCIM 2.0
		ScimUserCreated,
		ScimUserUpdated,
		ScimUserDeactivated,
		ScimUserDeleted,
		ScimAuthFailed,
		ScimUserReactivated,
		ScimGroupListed,
		ScimUserListed,
		ScimUserRetrieved,
		// SCIM bearer token lifecycle
		ScimBearerTokenProvisioned,
		ScimBearerTokenRotated,
		// User Defined Fields
		UdfDefinitionCreated,
		UdfDefinitionUpdated,
		UdfDefinitionDeleted,
		UdfFieldAdded,
		UdfFieldUpdated,
		UdfFieldRemoved,
		UdfFieldValueSaved,
		// Route Planning
		RouteCreated,
		RouteUpdated,
		RouteDeleted,
		RouteStarted,
		RouteCompleted,
		RouteCancelled,
		RoutePaused,
		RouteResumed,
		RouteStopCheckedIn,
		RouteStopCheckedOut,
		RouteStopSkipped,
		RouteDeviationDetected,
		RouteDeviationAcknowledged,
		// Check-In Timers
		CheckInTimerConfigCreated,
		CheckInTimerConfigUpdated,
		CheckInTimerConfigDeleted,
		CheckInTimerOverrideCreated,
		CheckInTimerOverrideUpdated,
		CheckInTimerOverrideDeleted,
		CheckInPerformed,
		CheckInTimerEnabledOnCall,
		CheckInTimerDisabledOnCall,
		// Calendar Check-In Attendance
		CalendarCheckInPerformed,
		CalendarCheckOutPerformed,
		CalendarCheckInUpdated,
		CalendarCheckInDeleted,
		CalendarAdminCheckInPerformed,
		// Log operations
		LogCreated,
		LogDeleted,
		// Communication Test operations
		CommunicationTestCreated,
		CommunicationTestUpdated,
		CommunicationTestDeleted,
		CommunicationTestRunStarted,
		// Weather Alerts
		WeatherAlertSourceCreated,
		WeatherAlertSourceUpdated,
		WeatherAlertSourceDeleted,
		WeatherAlertSourceEnabled,
		WeatherAlertSourceDisabled,
		WeatherAlertZoneCreated,
		WeatherAlertZoneUpdated,
		WeatherAlertZoneDeleted,
		WeatherAlertZoneEnabled,
		WeatherAlertZoneDisabled,
		WeatherAlertSettingsChanged
	}
}
