namespace Resgrid.Model
{
	public enum DepartmentSettingTypes
	{
		BigBoardMapZoomLevel = 1,
		BigBoardPageRefresh = 2,
		BigBoardMapCenterAddress = 3,
		BigBoardHideUnavailable = 4,
		BigBoardMapCenterGpsCoordinates = 5,
		RssFeedKeyForActiveCalls = 6,
		StripeCustomerId = 7,
		TestEnabled = 8,
		DisabledAutoAvailable = 9,
		TextToCallNumber = 10,
		TextToCallImportFormat = 11,
		TextToCallSourceNumbers = 12,
		EnableTextToCall = 13,
		EnableTextCommand = 14,
		InternalDispatchEmail = 15,
		UpdateTimestamp = 16,
		BrainTreeCustomerId = 17,
		PersonnelSortOrder = 18,
		UnitsSortOrder = 19,
		CallsSortOrder = 20,
		PersonnelListStatusSortOrder = 21,
		DispatchShiftInsteadOfGroup = 22,
		AutoSetStatusForShiftDispatchPersonnel = 23,
		ShiftCallDispatchPersonnelStatusToSet = 24,
		ShiftCallReleasePersonnelStatusToSet = 25,
		AllowSignupsForMultipleShiftGroups = 26,
		StaffingSuppressStaffingLevels = 27,
		MappingPersonnelLocationTTL = 28,
		MappingUnitLocationTTL = 29,
		MappingPersonnelAllowStatusWithNoLocationToOverwrite = 30,
		MappingUnitAllowStatusWithNoLocationToOverwrite = 31,
		ModuleSettings = 32,
		UnitDispatchAlsoDispatchToAssignedPersonnel = 33,
		UnitDispatchAlsoDispatchToGroup = 34,
	}
}
