namespace Resgrid.Model
{
	public enum SystemAuditTypes
	{
		Login = 0,
		Purchase = 1,
		ContactVerification = 2,
		TwoFactorEnabled = 3,
		TwoFactorDisabled = 4,
		TwoFactorLoginVerified = 5,
		TwoFactorRecoveryCodeUsed = 6,
		TwoFactorStepUpVerified = 7,
		SsoLogin = 8,
		SsoLoginFailed = 9,
		ScimOperation = 10,
		AccountDeletionRequested = 11,
		GdprDataExportRequested = 12,
		GdprDataExportDownloaded = 13,
		PasswordChanged = 14,
		PasswordResetByAdministrator = 15,
		PublicPasswordResetCompleted = 16,
		UsernameChanged = 17,
		EmailChanged = 18,
		SessionRevoked = 19,
		OtherSessionsRevoked = 20,
		AllSessionsRevoked = 21,
		ExternalIdentityLinked = 22,
		ExternalIdentityUnlinked = 23,
		PasswordResetLinkSentByAdministrator = 24,
		SessionHistoryPurged = 25,
		TwoFactorAuthenticatorReplaced = 26,
		AccountReauthenticated = 27,
		PasskeyRegistered = 28,
		PasskeyRevoked = 29,
		PasskeyRenamed = 30,
		PasskeyApprovalChanged = 31,
		FederatedMfaMappingTested = 32,
		MfaApprovalRequested = 33,
		MfaApprovalApproved = 34,
		MfaApprovalDenied = 35,
		FactorRecoveryStarted = 36,
		FactorRecoveryCompleted = 37,
		FactorRecoveryCanceled = 38,
		SecurityNoticeFailed = 39,
		SharedSessionStarted = 40,
		SharedSessionLocked = 41,
		SharedSessionUnlocked = 42,
		SharedSessionEnded = 43,
		MfaActivityReported = 44,
		ApprovalInstallationsDisabled = 45,
		FederatedMfaMappingChanged = 46
	}
}
