using System.Collections.Generic;

namespace Resgrid.Model
{
	public static class TimeZones
	{
		public static Dictionary<string, string> Zones = new Dictionary<string, string>()
															 {
																 {"Hawaiian Standard Time", "(GMT-10:00) Hawaii"},
																 {"Alaskan Standard Time", "(GMT-09:00) Alaska"},
																 {"Pacific Standard Time", "(GMT-08:00) Pacific Time (US, Canada & Tijuana)"},
																 {"US Mountain Standard Time", "(GMT-07:00) Arizona"},
																 {"Mountain Standard Time", "(GMT-07:00) Mountain Time (US &	Canada)"},
																 {"Central Standard Time", "(GMT-06:00) Central Time (US &	Canada)"},
																 {"Eastern Standard Time", "(GMT-05:00) Eastern	Time (US & Canada)"},
																 {"US Eastern Standard Time", "(GMT-05:00) Indiana (East)"},
																												{"Dateline Standard Time", "(GMT-12:00) International Date Line West"},
																												{"Samoa Standard Time", "(GMT-11:00) Midway Island & Samoa"},
																												{"Mountain Standard Time (Mexico)", "(GMT-07:00) Chihuahua, La Paz, Mazatlan"},
																												{"Central America Standard Time", "(GMT-06:00) Central America"},
																												{"Central Standard Time (Mexico)", "(GMT-06:00) Mexico City, Guadalajara, Monterrey"},
																												{"Canada Central Standard Time", "(GMT-06:00) Saskatchewan"},
																												{"SA Pacific Standard Time", "(UTC-05:00) Bogota, Lima, Quito"},
																												{"Venezuela Standard Time", "(GMT-04:30) Caracas"},
																												{"Atlantic Standard Time", "(GMT-04:00) Atlantic Time (Canada)"},
																												{"SA Western Standard Time", "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan"},
																												{"Pacific SA Standard Time", "(GMT-04:00) Santiago"},
																												{"Newfoundland Standard Time", "(GMT-03:30) Newfoundland"},
																												{"E. South America Standard Time", "(GMT-03:00) Brasilia"},
																												{"Argentina Standard Time", "(GMT-03:00) Buenos Aires"},
																												{"Greenland Standard Time", "(GMT-03:00) Greenland"},
																												{"Mid-Atlantic Standard Time", "(GMT-02:00) Mid-Atlantic"},
																												{"Azores Standard Time", "(GMT-01:00) Azores"},
																												//{"Cabo Verde Standard Time", "(GMT-01:00) Cabo Verde"},
																												{"Morocco Standard Time", "(GMT+00:00) Casablanca"},
																												{"GMT Standard Time", "(GMT+00:00) (UTC) Dublin, Edinburgh, Lisbon, London"},
																												{"Greenwich Standard Time", "(GMT+00:00) (UTC) Monrovia, Reykjavik"},
																												{"UTC", "(GMT+00:00) UTC"},
																												{"W. Europe Standard Time", "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
																												{"Central Europe Standard Time", "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague"},
																												{"Romance Standard Time", "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris"},
																												{"Central European Standard Time", "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb"},
																												{"W. Central Africa Standard Time", "(GMT+01:00) West Central Africa"},
																												{"GTB Standard Time", "(UTC+02:00) Athens, Bucharest"},
																												{"Egypt Standard Time", "(GMT+02:00) Cairo"},
																												{"South Africa Standard Time", "(UTC+02:00) Harare, Pretoria"},
																												{"FLE Standard Time", "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"},
																												{"Israel Standard Time", "(GMT+02:00) Jerusalem"},
																												{"Turkey Standard Time", "(GMT+03:00) Istanbul"},
																												{"Arabic Standard Time", "(GMT+03:00) Baghdad"},
																												{"Arab Standard Time", "(UTC+03:00) Kuwait, Riyadh"},
																												{"E. Europe Standard Time", "(GMT+03:00) Minsk"},
																												{"E. Africa Standard Time", "(GMT+03:00) Nairobi"},
																												{"Iran Standard Time", "(GMT+03:30) Tehran"},
																												{"Arabian Standard Time", "(GMT+04:00) Abu Dhabi, Muscat"},
																												{"Azerbaijan Standard Time", "(GMT+04:00) Baku"},
																												{"Russian Standard Time", "(UTC+04:00) Moscow, St. Petersburg, Volgograd"},
																												{"Georgian Standard Time", "(GMT+04:00) Tbilisi"},
																												{"Caucasus Standard Time", "(GMT+04:00) Yerevan"},
																												{"Afghanistan Standard Time", "(GMT+04:30) Kabul"},
																												{"Pakistan Standard Time", "(GMT+05:00) Islamabad, Karachi"},
																												{"West Asia Standard Time", "(GMT+05:00) Tashkent"},
																												{"India Standard Time", "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi"},
																												{"Sri Lanka Standard Time", "(GMT+05:30) Sri Jayawardenepura"},
																												{"Nepal Standard Time", "(GMT+05:45) Kathmandu"},
																												{"Central Asia Standard Time", "(GMT+06:00) Astana, Almaty"},
																												{"Bangladesh Standard Time", "(GMT+06:00) Dhaka"},
																												{"Ekaterinburg Standard Time", "(GMT+06:00) Ekaterinburg"},
																												{"Myanmar Standard Time", "(GMT+06:30) Rangoon"},
																												{"SE Asia Standard Time", "(UTC+07:00) Bangkok, Hanoi, Jakarta"},
																												{"N. Central Asia Standard Time", "(GMT+07:00) Novosibirsk"},
																												{"China Standard Time", "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi"},
																												{"North Asia Standard Time", "(GMT+08:00) Krasnoyarsk"},
																												{"Singapore Standard Time", "(UTC+08:00) Kuala Lumpur, Singapore"},
																												{"W. Australia Standard Time", "(GMT+08:00) Perth"},
																												{"Taipei Standard Time", "(GMT+08:00) Taipei"},
																												{"Ulaanbaatar Standard Time", "(GMT+08:00) Ulaan Bataar"},
																												{"North Asia East Standard Time", "(GMT+09:00) Irkutsk"},
																												{"Tokyo Standard Time", "(UTC+09:00) Osaka, Sapporo, Tokyo"},
																												{"Korea Standard Time", "(GMT+09:00) Seoul"},
																												{"Cen. Australia Standard Time", "(GMT+09:30) Adelaide"},
																												{"AUS Central Standard Time", "(GMT+09:30) Darwin"},
																												{"E. Australia Standard Time", "(GMT+10:00) Brisbane"},
																												{"AUS Eastern Standard Time", "(UTC+10:00) Canberra, Melbourne, Sydney"},
																												{"West Pacific Standard Time", "(UTC+10:00) Guam, Port Moresby"},
																												{"Tasmania Standard Time", "(GMT+10:00) Hobart"},
																												{"Yakutsk Standard Time", "(GMT+10:00) Yakutsk"},
																												{"Central Pacific Standard Time", "(UTC+11:00) Solomon Is., New Caledonia"},
																												{"Vladivostok Standard Time", "(GMT+11:00) Vladivostok"},
																												{"New Zealand Standard Time", "(UTC+12:00) Auckland, Wellington"},
																												{"Fiji Standard Time", "(GMT+12:00) Fiji"},
																												{"Magadan Standard Time", "(GMT+12:00) Magadan"},
																												{"Tonga Standard Time", "(GMT+13:00) Nuku'alofa"}
															 };
	}
}
