using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using FluentAssertions;
using FluentMigrator;
using FluentMigrator.Runner;
using FluentMigrator.Runner.Initialization;
using Microsoft.Extensions.DependencyInjection;
using Moq;
using Npgsql;
using NUnit.Framework;
using Resgrid.Config;
using Resgrid.Model;
using Resgrid.Model.Repositories;
using Resgrid.Model.Repositories.Connection;
using Resgrid.Model.Repositories.Queries;
using Resgrid.Providers.MigrationsPg.Migrations;
using Resgrid.Repositories.DataRepository;
using Resgrid.Repositories.DataRepository.Servers.SqlServer;
using Resgrid.Repositories.DataRepository.Transactions;

namespace Resgrid.Tests.Rms
{
	[TestFixture, NonParallelizable]
	public class RmsPostgreSqlDatabaseTests
	{
		private string _master, _connection, _database;
		private DatabaseTypes _previousType;

		[OneTimeSetUp]
		public async Task MigrateOnlyAnIsolatedTestDatabase()
		{
			_master = Environment.GetEnvironmentVariable("RESGRID_RMS_POSTGRES_TEST_CONNECTION");
			if (string.IsNullOrWhiteSpace(_master)) Assert.Ignore("Set RESGRID_RMS_POSTGRES_TEST_CONNECTION to an isolated PostgreSQL test server.");
			_previousType = DataConfig.DatabaseType; DataConfig.DatabaseType = DatabaseTypes.Postgres;
			_database = "rms_verification_" + Guid.NewGuid().ToString("N");
			await using var master = new NpgsqlConnection(_master);
			await master.ExecuteAsync($"CREATE DATABASE {_database}");
			_connection = new NpgsqlConnectionStringBuilder(_master) { Database = _database }.ConnectionString;
			await using (var db = new NpgsqlConnection(_connection))
				await db.ExecuteAsync(@"CREATE EXTENSION citext;
CREATE TABLE departments (departmentid integer PRIMARY KEY); INSERT INTO departments VALUES (11),(12);
CREATE TABLE departmentsettings (departmentsettingid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,departmentid integer NOT NULL,settingtype integer NOT NULL,setting text NOT NULL);
CREATE TABLE workflowruns (workflowrunid citext PRIMARY KEY,workflowid citext NOT NULL,departmentid integer NOT NULL,status integer NOT NULL,completedon timestamp,inputpayload text,errormessage text);
CREATE TABLE workflowrunlogs (workflowrunlogid citext PRIMARY KEY,workflowrunid citext NOT NULL,renderedoutput text,actionresult text,errormessage text);");
			var versions = new HashSet<long> { 48, 49, 124, 142, 143, 144, 145, 150, 151, 153, 154, 155, 156, 157, 160, 164, 165, 166, 167, 168, 169, 170, 171, 173 };
			var migrations = typeof(M0150_AddRmsRecordsCorePg).Assembly.GetTypes().Where(t => typeof(IMigration).IsAssignableFrom(t) && !t.IsAbstract)
				.Where(t => t.GetCustomAttributes(typeof(MigrationAttribute), false).Cast<MigrationAttribute>().Any(a => versions.Contains(a.Version)))
				.Select(t => (IMigration)Activator.CreateInstance(t)).ToList();
			migrations.Should().HaveCount(versions.Count, "every selected shipped migration must be exercised");
			var source = new Mock<IMigrationSource>(); source.Setup(s => s.GetMigrations()).Returns(migrations);
			using var services = new ServiceCollection().AddFluentMigratorCore().ConfigureRunner(r => r.AddPostgres().WithGlobalConnectionString(_connection)).AddSingleton(source.Object).BuildServiceProvider();
			services.GetRequiredService<IMigrationRunner>().MigrateUp();
			TestContext.Progress.WriteLine("Migrated isolated PostgreSQL database: " + _database);
		}

		[OneTimeTearDown]
		public async Task RemoveOnlyTheDatabaseCreatedByThisFixture()
		{
			if (_database == null) return;
			DataConfig.DatabaseType = _previousType;
			if (!_database.StartsWith("rms_verification_", StringComparison.Ordinal) || _database.Length != 49 || !Guid.TryParseExact(_database.Substring(17), "N", out _)) throw new InvalidOperationException("Unexpected PostgreSQL test database name.");
			NpgsqlConnection.ClearAllPools();
			await using var master = new NpgsqlConnection(_master);
			await master.ExecuteAsync($"DROP DATABASE {_database} WITH (FORCE)");
		}

		private IConnectionProvider Connections()
		{
			var provider = new Mock<IConnectionProvider>(); provider.Setup(p => p.Create()).Returns(() => new NpgsqlConnection(_connection)); return provider.Object;
		}

		private static IQueryFactory WriteQueries()
		{
			var list = new Mock<Resgrid.Model.Repositories.Queries.Contracts.IQueryList>();
			var queries = new System.Collections.Concurrent.ConcurrentDictionary<Type, Resgrid.Model.Repositories.Queries.Contracts.IQuery>();
			queries[typeof(Resgrid.Repositories.DataRepository.Queries.Common.InsertQuery)] = new Resgrid.Repositories.DataRepository.Queries.Common.InsertQuery(new PostgreSqlConfiguration());
			queries[typeof(Resgrid.Repositories.DataRepository.Queries.Common.UpdateQuery)] = new Resgrid.Repositories.DataRepository.Queries.Common.UpdateQuery(new PostgreSqlConfiguration());
			list.Setup(l => l.RetrieveQueryList()).Returns(queries); return new Resgrid.Repositories.DataRepository.Queries.QueryFactory(list.Object);
		}

		private async Task<string> SeedOperational()
		{
			var id = Guid.NewGuid().ToString(); var old = DateTime.UtcNow.AddYears(-10);
			var connections = Connections(); using var unit = new UnitOfWork(connections);
			await new RmsOperationalRecordsRepository(connections, new PostgreSqlConfiguration(), unit, WriteQueries()).InsertAsync(new RmsOperationalRecord
			{
				RmsOperationalRecordId = id, DepartmentId = 11, ProtectionId = id, DefinitionKey = RmsDefinitionKeys.Training, DefinitionVersion = 1,
				State = (int)RmsRecordState.Finalized, AuthorUserId = "officer", OwnerUserId = "officer", CreatedByUserId = "officer", DraftReference = id.Substring(0, 20), CreatedOn = old, ModifiedOn = old, FinalizedOn = old, RowVersion = 1
			}, CancellationToken.None, true);
			return id;
		}

		[Test]
		public async Task Purge_erases_revisions_and_attachment_bytes_then_acknowledges_the_exact_purge()
		{
			var id = await SeedOperational(); var connections = Connections(); using var unit = new UnitOfWork(connections);
			var revision = Guid.NewGuid().ToString(); var attachment = Guid.NewGuid().ToString();
			await new RmsRevisionsRepository(connections, new PostgreSqlConfiguration(), unit, WriteQueries()).InsertAsync(new RmsRevision { RmsRevisionId = revision, DepartmentId = 11, ProtectionId = revision, RecordId = id, RecordKind = (int)RmsRecordKind.Operational, RevisionNumber = 1, DefinitionKey = RmsDefinitionKeys.Training, DefinitionVersion = 1, SnapshotJson = "{\"sensitive\":\"old report\"}", Checksum = new string('a', 64), ActorUserId = "officer", CreatedOn = DateTime.UtcNow.AddYears(-10) }, CancellationToken.None, true);
			await new RmsRecordAttachmentsRepository(connections, new PostgreSqlConfiguration(), unit, WriteQueries()).InsertAsync(new RmsRecordAttachment { RmsRecordAttachmentId = attachment, DepartmentId = 11, ProtectionId = attachment, RecordId = id, FileName = "scene.txt", ContentType = "text/plain", Data = new byte[] { 1, 2, 3 }, ByteSize = 3, Checksum = new string('b', 64), UploadedByUserId = "officer", UploadedOn = DateTime.UtcNow.AddYears(-10), CreatedOn = DateTime.UtcNow.AddYears(-10), ModifiedOn = DateTime.UtcNow.AddYears(-10), ScanState = (int)RmsAttachmentScanState.Clean, RowVersion = 1 }, CancellationToken.None, true);
			var repository = new RmsRetentionRepository(connections, new PostgreSqlConfiguration(), unit, WriteQueries());
			var result = await repository.PurgeAsync(11, id, RmsRecordKind.Operational, 1, DateTime.UtcNow);
			result.Purged.Should().BeTrue(result.Reason); result.SearchErasurePending.Should().BeTrue();
			await using var db = new NpgsqlConnection(_connection);
			(await db.ExecuteScalarAsync<string>("SELECT snapshotjson FROM rmsrevisions WHERE rmsrevisionid=@Id", new { Id = revision })).Should().Be("{}");
			(await db.ExecuteScalarAsync<int>("SELECT count(*) FROM rmsrecordattachments WHERE recordid=@Id", new { Id = id })).Should().Be(0);
			var target = (await repository.GetPendingSearchErasuresAsync(100)).Single(t => t.RecordId == id);
			(await repository.CompleteSearchErasureAsync(target, DateTime.UtcNow)).Should().BeTrue();
			(await repository.CompleteSearchErasureAsync(target, DateTime.UtcNow)).Should().BeFalse();
			Func<Task> late = () => new RmsRevisionsRepository(connections, new PostgreSqlConfiguration(), unit, WriteQueries()).InsertAsync(new RmsRevision { RecordId = id, DepartmentId = 11 }, CancellationToken.None, true);
			await late.Should().ThrowAsync<InvalidOperationException>();
		}

		[Test]
		public async Task Concurrent_command_reservations_have_one_owner_and_survive_a_new_connection()
		{
			var id = await SeedOperational(); var key = new string('c', 64); var checksum = new string('d', 64); var connections = Connections();
			using var firstUnit = new UnitOfWork(connections); using var secondUnit = new UnitOfWork(connections);
			var first = new RmsCommandReceiptsRepository(connections, new PostgreSqlConfiguration(), firstUnit, WriteQueries());
			var second = new RmsCommandReceiptsRepository(connections, new PostgreSqlConfiguration(), secondUnit, WriteQueries());
			var owner1 = Guid.NewGuid().ToString(); var owner2 = Guid.NewGuid().ToString();
			var outcomes = await Task.WhenAll(first.ReserveAsync(11, key, id, checksum, owner1), second.ReserveAsync(11, key, id, checksum, owner2));
			outcomes.Count(won => won).Should().Be(1);
			(await second.GetAsync(11, key)).IsPending.Should().BeTrue();
			(await first.CompleteAsync(12, key, id, checksum, outcomes[0] ? owner1 : owner2)).Should().BeFalse();
			(await second.CompleteAsync(11, key, id, checksum, outcomes[0] ? owner2 : owner1)).Should().BeFalse();
			(await second.CompleteAsync(11, key, id, checksum, outcomes[0] ? owner1 : owner2)).Should().BeTrue();
			(await first.GetAsync(11, key)).IsPending.Should().BeFalse();
		}

		[Test]
		public async Task Expired_shares_do_not_grant_scope_or_counts()
		{
			var id = await SeedOperational(); var share = Guid.NewGuid().ToString(); var connections = Connections(); using var unit = new UnitOfWork(connections);
			await using var db = new NpgsqlConnection(_connection);
			await db.ExecuteAsync("INSERT INTO rmsrecordgroupscopes (departmentid,recordid,departmentgroupid,anchortype,createdon) VALUES (11,@Id,808,@Anchor,now()); INSERT INTO rmsrecordshares (rmsrecordshareid,departmentid,protectionid,recordid,departmentgroupid,grantedbyuserid,grantedon,createdon,modifiedon) VALUES (@Share,11,@Share,@Id,808,'officer',now(),now(),now())", new { Id = id, Share = share, Anchor = (int)RmsGroupScopeAnchorType.Share });
			var scopes = new RmsRecordGroupScopesRepository(connections, new PostgreSqlConfiguration(), unit, WriteQueries());
			var records = new RmsOperationalRecordsRepository(connections, new PostgreSqlConfiguration(), unit, WriteQueries());
			(await scopes.GetForRecordAsync(11, id)).Should().ContainSingle();
			(await records.CountVisibleAsync(11, new[] { (int)RmsRecordState.Finalized }, new List<int> { 808 }, "reader")).Should().Be(1);
			await db.ExecuteAsync("UPDATE rmsrecordshares SET expireson=now()-interval '1 second' WHERE rmsrecordshareid=@Share", new { Share = share });
			(await scopes.GetForRecordsAsync(11, new[] { id })).Should().BeEmpty();
			(await scopes.GetEffectiveSharesAsync(11, new[] { 808 })).Should().BeEmpty();
			(await records.CountVisibleAsync(11, new[] { (int)RmsRecordState.Finalized }, new List<int> { 808 }, "reader")).Should().Be(0);
		}

		[Test]
		public async Task Precise_projection_paging_does_not_repeat_the_cursor_row()
		{
			var first = Guid.NewGuid().ToString(); var second = Guid.NewGuid().ToString(); var ids = new[] { first, second }.OrderBy(s => s, StringComparer.Ordinal).ToArray();
			await using var db = new NpgsqlConnection(_connection);
			foreach (var id in ids) await db.ExecuteAsync("INSERT INTO rmsrecordsearchprojections (rmsrecordsearchprojectionid,departmentid,protectionid,sourcetype,sourceid,definitionkey,state,recordcreatedon,createdon,modifiedon,rowversion) VALUES (@Id,11,@Id,1,@Id,'system.training',4,now(),now(),timestamp '2050-01-01 12:34:56.123456',1)", new { Id = id });
			var connections = Connections(); using var unit = new UnitOfWork(connections);
			var repository = new RmsRecordSearchProjectionsRepository(connections, new PostgreSqlConfiguration(), unit, WriteQueries());
			var page = (await repository.GetModifiedSinceAsync(11, new DateTime(2050, 1, 1, 0, 0, 0, DateTimeKind.Utc), 1)).Single();
			page.RmsRecordSearchProjectionId.Should().Be(ids[0]);
			var next = (await repository.GetModifiedSinceAsync(11, page.ModifiedOn, 1, page.RmsRecordSearchProjectionId)).Single();
			next.RmsRecordSearchProjectionId.Should().Be(ids[1]);
			(await repository.GetModifiedSinceAsync(11, next.ModifiedOn, 1, next.RmsRecordSearchProjectionId)).Should().BeEmpty();
		}
	}
}
