const assert = require('node:assert/strict');
const path = require('node:path');
const { chromium } = require('./browser-launch.cjs').playwright();
const script = path.resolve(__dirname, '../../../Web/Resgrid.Web/wwwroot/js/app/internal/checklists/checklists.js');
const itemId = '11111111-1111-1111-1111-111111111111';
const otherId = '22222222-2222-2222-2222-222222222222';
const item = { Id: itemId, Name: 'Equipment works', Type: 0, Required: true, Critical: true, AllowNotApplicable: true, RequireNoteOnFail: true, Weight: 1, PassingValue: 'true', Options: [] };
const definition = { Name: 'Shift readiness', Category: 0, TargetType: 0, PassThreshold: 100, Sections: [{ Id: '33333333-3333-3333-3333-333333333333', Name: 'Safety', Items: [item] }] };
const htmlJson = value => JSON.stringify(value).replace(/</g, '\\u003c');
(async () => {
    const browser = await chromium.launch(require('./browser-launch.cjs').launchOptions());
    try {
        const page = await browser.newPage();
        const errors = []; page.on('pageerror', error => errors.push(error.message));
        await page.route('https://checklists.test/**', route => route.fulfill({ contentType: 'text/html', body: '<html><body></body></html>' }));
        await page.goto('https://checklists.test/');
        await page.setContent(`<div id="checklist-error" hidden></div><form id="checklist-editor" action="/save"><input name="id" value="definition"><input name="revision" value="1"><input name="__RequestVerificationToken" value="csrf"><input name="formJson"><div id="checklist-builder"></div><button type="submit">Save draft</button></form><script id="checklist-form-data" type="application/json">${htmlJson(definition)}</script>`);
        await page.evaluate(() => { window.requests = []; window.fetch = async (url, options) => { requests.push({ url, fields: Object.fromEntries(options.body.entries()) }); return { ok: true, status: 200, json: async () => ({ revision: 2 }) }; }; });
        await page.addScriptTag({ path: script });
        await page.getByLabel('Checklist name', { exact: true }).fill('Warehouse readiness');
        await page.getByLabel('Answer type', { exact: true }).selectOption('3');
        await page.getByLabel('Minimum passing value (optional if maximum is set)', { exact: true }).fill('5');
        await page.getByLabel('Maximum passing value (optional if minimum is set)', { exact: true }).fill('10');
        await page.getByRole('button', { name: 'Add item', exact: true }).click();
        await page.getByLabel('Question / check', { exact: true }).nth(1).fill('<img src=x onerror="window.pwned=true">');
        await page.getByRole('button', { name: 'Move item up', exact: true }).nth(1).click();
        await page.getByRole('button', { name: 'Save draft', exact: true }).click();
        const posted = await page.evaluate(() => requests[0].fields);
        const saved = JSON.parse(posted.formJson);
        assert.equal(saved.Name, 'Warehouse readiness');
        assert.equal(saved.Sections[0].Items[1].Id, itemId, 'Reordering preserves item identity');
        assert.equal(saved.Sections[0].Items[1].Minimum, 5);
        assert.equal(saved.Sections[0].Items[1].Type, 3, 'Type selectors serialize enum numbers');
        assert.equal(posted.__RequestVerificationToken, 'csrf');
        assert.equal(await page.evaluate(() => window.pwned), undefined);

        const conditional = { ...item, Id: otherId, Name: 'Failure detail', Type: 5, Critical: false, Required: false, VisibleWhen: { ItemId: itemId, EqualsValue: 'fail' }, RequiredWhen: { ItemId: itemId, EqualsValue: 'fail' } };
        const run = { Completion: { Id: '44444444-4444-4444-4444-444444444444' }, Form: { ...definition, Sections: [{ ...definition.Sections[0], Items: [item, conditional] }] }, Input: { Revision: 1, Answers: [], Note: null }, Files: [] };
        await page.setContent(`<div id="checklist-error" hidden></div><div id="checklist-saved" hidden></div><form id="checklist-run" action="/run/save" data-upload="/upload" data-remove="/remove" data-evidence="/evidence"><input name="id" value="${run.Completion.Id}"><input name="inputJson"><input name="__RequestVerificationToken" value="csrf"><div id="checklist-answers"></div><button type="submit" name="submit" value="false">Save progress</button><button type="submit" name="submit" value="true">Submit</button></form><script id="checklist-run-data" type="application/json">${htmlJson(run)}</script>`);
        await page.evaluate(() => { window.requests = []; window.fetch = (url, options) => new Promise(resolve => requests.push({ url, fields: Object.fromEntries(options.body.entries()), resolve })); });
        await page.addScriptTag({ path: script });
        assert.equal(await page.getByText('Failure detail', { exact: true }).isVisible(), false);
        await page.getByLabel('Answer status', { exact: true }).nth(0).selectOption('1');
        await page.getByLabel('Answer', { exact: true }).nth(0).selectOption('fail');
        assert.equal(await page.getByText('Failure detail', { exact: true }).isVisible(), true);
        await page.getByLabel('Answer status', { exact: true }).nth(1).selectOption('1');
        await page.getByLabel('Answer', { exact: true }).nth(1).fill('Fault isolated');
        await page.getByLabel('Answer', { exact: true }).nth(0).selectOption('pass');
        assert.equal(await page.getByText('Failure detail', { exact: true }).isVisible(), false);
        await page.getByRole('button', { name: 'Save progress', exact: true }).click();
        await page.getByRole('button', { name: 'Save progress', exact: true }).click();
        assert.equal(await page.evaluate(() => requests.length), 1, 'Only one save may be in flight');
        const first = JSON.parse(await page.evaluate(() => requests[0].fields.inputJson));
        assert.equal(first.Answers[1].Status, 0); assert.equal(first.Answers[1].Value, null, 'Hidden answers are cleared before posting');
        await page.getByLabel('Completion / handover note', { exact: true }).fill('Typed while save is in flight');
        await page.evaluate(() => requests[0].resolve({ ok: true, status: 200, json: async () => ({ revision: 2 }) }));
        await page.getByRole('button', { name: 'Save progress', exact: true }).click();
        const second = JSON.parse(await page.evaluate(() => requests[1].fields.inputJson));
        assert.equal(second.Revision, 2); assert.equal(second.Note, 'Typed while save is in flight');
        await page.evaluate(() => requests[1].resolve({ ok: false, status: 409, json: async () => ({ message: 'Reload before saving.' }) }));
        await page.locator('#checklist-error:not([hidden])').waitFor();
        assert.match(await page.locator('#checklist-error').textContent(), /Reload/);
        assert.equal(await page.getByLabel('Completion / handover note', { exact: true }).inputValue(), 'Typed while save is in flight');
        assert.deepEqual(errors, []);
        console.log('PASS: builder types and ordering, escaped content, conditional visibility, serialized saves, revision updates, CSRF, conflict preserves unsaved work.');
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
